FROM eclipse-temurin:23-jre-ubi9-minimal

# Copy App Resources
COPY import_tokens/StoredCredential /usr/src/google-cal-sync/import_tokens/
COPY reader_tokens/StoredCredential /usr/src/google-cal-sync/reader_tokens/
COPY ./target/google-cal-sync-1.1-SNAPSHOT-jar-with-dependencies.jar /usr/src/google-cal-sync/
COPY .env /usr/src/google-cal-sync/

# Configure Cronjob
RUN microdnf -y update && microdnf -y install cronie
COPY src/main/cron/cal-sync-cron /etc/cron.d/cal-sync-cron
RUN crontab /etc/cron.d/cal-sync-cron

WORKDIR /usr/src/google-cal-sync
CMD ["crond", "-n"]